10 PRINT "MAMOTH MAZE in 2.5k Bytes By G.T.Relf"
20 REM SET STARTING POSITION (EAST, WEST, DOWN):
30 X=103:Y=97:Z=1
40  REM SET THREASHOLD
50    T=0.3
60    REM RANDOMIZE FOR EARTHQUAKES
70    RANDOM
80    REM INSERT ANY OTHER INITIALISING STATEMENTS HERE.
90    REM MAIN LOOP:
100  REM COMPUTE PROPERTIES OF CURRENT LOCATION
110  GOSUB 250
  REM GET COMMAND & BRANCH ACCORDINGLY:
    INPUT "COMMAND"; CM$
    CM$=LEFT(CM$,1)
    IF CM$="N" THEN 490
      IF CM$="E" THEN 530
    IF CM$="W" THEN 570
          IF CM$="S" THEN 610
    IF CM$="U" THEN 650
              IF CM$="D" THEN 690
                PRINT "IMPOSSIBLE!"
                GOTO 110
                REM END OF MAIN LOOP
          240 REM COMPUTE ATTRIBUTES OF CURRENT LOCATION:
          250 V1=INT(W*1000)
          260 IF V1>35 AND V1<39 AND Z>1 THEN PRINT "HERE IS A CROCK OF GOLD!"
            270 REM (YOU WONT FIND CROCKS OF GOLD JUST LYING ON THE GROUND!)
            280 REM INSERT OTHER ATTRIBUTE TESTS HERE.
            290 REM CHECK FOR EARTHQUAKES:
            300 IF RND(1000)=9 THEN PRINT "RUMBLE, RUMBLE...": T=T+0.2*RND(0)-0.1
              310 REM INSERT OTHER LOCATION-DEPENDANT TESTS HERE.
              320 REM IDENTIFY CORRIDORS FROM CURRENT LOCATION (CHANGES W):
              330 IF Z=1 THEN 440
                340 PRINT "CORRIDORS: "; : NC=0
                350 X=X+1: GOSUB 720 : IF W<T THEN PRINT "E":NC=NC+1
      
